# -- 코드를 입력하세요
# SELECT DATE_FORMAT(A.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, 
# (CASE WHEN A.ONLINE_SALE_ID = B.OFFLINE_SALE_ID
# THEN NULL ELSE A.USER_ID
# END) AS USER_ID, A.USER_ID, B.SALES_AMOUNT
# FROM ONLINE_SALE A
# JOIN OFFLINE_SALE B
# ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE DATE_FORMAT(A.SALES_DATE, "%Y-%m") = "2022-03"
# ORDER BY A.SALES_DATE, A.USER_ID

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE 
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-03"

UNION ALL 

SELECT DATE_FORMAT(SALES_DATE, "%Y-%m-%d") AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-03"

ORDER BY SALES_DATE, PRODUCT_ID, USER_ID