-- 코드를 입력하세요
SELECT A.ANIMAL_ID, B.ANIMAL_TYPE, B.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE "Intact%" and (B.SEX_UPON_OUTCOME LIKE "Spayed%" || B.SEX_UPON_OUTCOME LIKE "Neutered%")
