SET @HOUR := -1;

SELECT @HOUR := @HOUR + 1 AS HOUR
    , (SELECT COUNT(*) FROM ANIMAL_OUTS 
      WHERE HOUR(DATETIME) = @HOUR) AS COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23
ORDER BY HOUR
# 하나의 변수를 생성할 때 사용하는게 SET