-- 코드를 입력하세요
SET @HOUR := 8;

SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN 
(
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) BETWEEN 9 AND 19
)
GROUP BY HOUR
ORDER BY HOUR