# SET @HOUR := 8;

# SELECT @HOUR := @HOUR + 1
# FROM ANIMAL_OUTS
# WHERE @HOUR < 19

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) BETWEEN "09:00" AND "19:00"
)
GROUP BY HOUR
ORDER BY HOUR